version: '3'

services:

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    image: enriqueps/nginx:prod
    container_name: nginx
    entrypoint: wait-for app:3000 -t 20 -- nginx -g 'daemon off;'
    networks:
      - network
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: node
      dockerfile: Dockerfile.prod
    container_name: app
    entrypoint: wait-for db:3306 -t 20 -- ./docker-entrypoint.sh
    networks:
      - network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network

networks:
  network:
    driver: bridge